language: ruby
rvm:
- 2.2.1
deploy:
  provider: rubygems
  api_key:
    secure: MU7uLfXgToLsBwVVY6yWDVEwziQhGou7tTDFe5Wj21djanGNzj9KG12MyQgwiTzm6J2PKzu9aIKRh6EtBWZF69XxeLuUrdGeq/sqDoCXUenyysKhJMwGMQRzwCdO8JigzNOKpnVX7+FpPwap+6RmoKQze6ZZ3GG0zuOKLHyiI4Q=
  gem: number_crusher
  on:
    tags: true
    repo: VAGAScom/number_crusher
